#!perl

# DATE
# VERSION

# FRAGMENT id=shcompgen-hint command=_cpanm-task

use strict 'subs', 'vars';
use warnings;

use App::lcpan::Call;

my @new_argv;
for my $arg (@ARGV) {
    # not a module name
    unless ($arg =~ /\A[A-Za-z0-9_]+(::[A-Za-z0-9_]+)*\z/) {
        push @new_argv, $arg;
        next;
    }
    my $mod = $arg =~ /^Task::/ ? $arg : "Task::$arg";
    push @new_argv, $mod;
}

print join(" ", "cpanm", @new_argv), "\n" if $ENV{DEBUG};
system {"cpanm"} "cpanm", @new_argv;

# ABSTRACT: Install Task modules
# PODNAME:

=head1 DESCRIPTION

L<cpanm-task> is a simplistic wrapper over L<cpanm>. This command:

 % cpanm-task -n Foo

is equivalent to:

 % cpanm -n Task::Foo

Currently that's about it. This script only gives shell tab completion
convenience.


=head1 SEE ALSO

L<cpanm-cpanmodules> from L<App::cpanm::cpanmodules>

=cut
